create table if not exists public.dudu_orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  delivery_date date not null,
  delivery_slot text not null,
  destination text not null,
  note text default '',
  merchant text not null,
  status text not null default 'ORDER',
  created_at timestamptz not null default now()
);
create index if not exists dudu_orders_slot_idx on public.dudu_orders(delivery_date, delivery_slot);

create table if not exists public.dudu_slot_settings (
  id boolean primary key default true,
  capacity integer not null default 4 check (capacity between 1 and 20)
);
insert into public.dudu_slot_settings(id,capacity) values(true,4) on conflict (id) do nothing;

create or replace function public.create_dudu_order(
  p_order_id text,p_delivery_date date,p_delivery_slot text,p_destination text,p_note text,p_merchant text
) returns jsonb
language plpgsql
security definer
as $$
declare
  cap integer;
  used integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_delivery_date::text || '|' || p_delivery_slot));
  select capacity into cap from public.dudu_slot_settings where id=true;
  select count(*) into used from public.dudu_orders
    where delivery_date=p_delivery_date and delivery_slot=p_delivery_slot and status <> 'CANCELLED';
  if used >= cap then
    return jsonb_build_object('ok',false,'reason','FULL','capacity',cap,'used',used);
  end if;
  insert into public.dudu_orders(order_id,delivery_date,delivery_slot,destination,note,merchant)
  values(p_order_id,p_delivery_date,p_delivery_slot,p_destination,coalesce(p_note,''),p_merchant);
  return jsonb_build_object('ok',true,'capacity',cap,'used',used+1);
end;
$$;

alter table public.dudu_orders enable row level security;
alter table public.dudu_slot_settings enable row level security;
-- Operations fields for the pilot order workflow.
alter table public.dudu_orders
  add column if not exists assigned_robot text,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists dudu_orders_status_idx
  on public.dudu_orders(status, created_at desc);


-- Fleet state for the DUDU pilot. This is the integration layer for the real robot platform.
create table if not exists public.dudu_robots (
  id bigint generated by default as identity primary key,
  robot_id text unique not null,
  name text not null,
  status text not null default 'AVAILABLE',
  battery integer not null default 100 check (battery between 0 and 100),
  mode text not null default 'MANUAL_PILOT',
  order_id text,
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists dudu_robots_status_idx on public.dudu_robots(status);

insert into public.dudu_robots(robot_id,name,status,battery,mode)
values
 ('DUDU-01','DUDU-01','DELIVERING',82,'MANUAL_PILOT'),
 ('DUDU-02','DUDU-02','AVAILABLE',94,'MANUAL_PILOT'),
 ('DUDU-03','DUDU-03','CHARGING',62,'CHARGING')
on conflict (robot_id) do nothing;

alter table public.dudu_robots enable row level security;
