create table if not exists public.dudu_orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  delivery_date date not null,
  delivery_slot text not null,
  destination text not null,
  note text default '',
  merchant text not null,
  status text not null default 'ORDER',
  created_at timestamptz not null default now()
);
create index if not exists dudu_orders_slot_idx on public.dudu_orders(delivery_date, delivery_slot);
alter table public.dudu_orders enable row level security;
